
package oca.project;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * Form that allows running various reports 
 */
public class ReportForm extends javax.swing.JFrame {
    
    private ArrayList<Person> person = new ArrayList();
    private ArrayList<PayrollReportItem> payrollReportList = new ArrayList();
    
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form ReportForm
     * @param person
     * @param payrollReportList
     */
    public ReportForm(ArrayList<Person> person, ArrayList<PayrollReportItem> payrollReportList) {
        initComponents();
        this.person = person;
        this.payrollReportList = payrollReportList;
        cboName.removeAllItems();
        for (Person p: person){
            cboName.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgMessage = new javax.swing.JOptionPane();
        btnPaymentForPeriod = new javax.swing.JButton();
        btnBonusReport = new javax.swing.JButton();
        btnPaymentHistoryForPerson = new javax.swing.JButton();
        btnFortnighlyPayments = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMonthlyPayments = new javax.swing.JButton();
        cboName = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFirstDate = new javax.swing.JTextField();
        txtSecondDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReport = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblAssign = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnPaymentForPeriod.setBackground(new java.awt.Color(153, 255, 153));
        btnPaymentForPeriod.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnPaymentForPeriod.setText("All payments for a period");
        btnPaymentForPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentForPeriodActionPerformed(evt);
            }
        });

        btnBonusReport.setBackground(new java.awt.Color(153, 255, 153));
        btnBonusReport.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnBonusReport.setText("Bonuses report");
        btnBonusReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBonusReportActionPerformed(evt);
            }
        });

        btnPaymentHistoryForPerson.setBackground(new java.awt.Color(153, 255, 153));
        btnPaymentHistoryForPerson.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnPaymentHistoryForPerson.setText("Payment history by person");
        btnPaymentHistoryForPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentHistoryForPersonActionPerformed(evt);
            }
        });

        btnFortnighlyPayments.setBackground(new java.awt.Color(153, 255, 153));
        btnFortnighlyPayments.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnFortnighlyPayments.setText("List Fortnightly Payments");
        btnFortnighlyPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFortnighlyPaymentsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Payroll Reports");

        btnMonthlyPayments.setBackground(new java.awt.Color(153, 255, 153));
        btnMonthlyPayments.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnMonthlyPayments.setText("List Monthly Payments");
        btnMonthlyPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyPaymentsActionPerformed(evt);
            }
        });

        cboName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cboName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBack.setBackground(new java.awt.Color(153, 255, 153));
        btnBack.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("First Date:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Second Date:");

        txtFirstDate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtSecondDate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtReport.setColumns(20);
        txtReport.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtReport.setRows(5);
        txtReport.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtReport.setEnabled(false);
        jScrollPane1.setViewportView(txtReport);

        lblAssign.setBackground(new java.awt.Color(102, 102, 255));
        lblAssign.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        lblAssign.setForeground(new java.awt.Color(102, 102, 102));
        lblAssign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAssign.setText("Best IT Paytoll");
        lblAssign.setAutoscrolls(true);
        lblAssign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAssign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnPaymentForPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnBonusReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnPaymentHistoryForPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnFortnighlyPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnMonthlyPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cboName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(80, 80, 80)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtSecondDate)
                                                        .addComponent(txtFirstDate)))
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(261, 261, 261)
                                        .addComponent(jLabel4)))))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFirstDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSecondDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPaymentForPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBonusReport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(cboName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPaymentHistoryForPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFortnighlyPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMonthlyPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    //event handler for the Back button that closes the current form and displays the main form 
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainForm form = new MainForm(getPerson());
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    //event handler for the button that displays all payments made within a period between two dates
    private void btnPaymentForPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentForPeriodActionPerformed
        //Prints report from two dates
        txtReport.setText(""); //Refreshes the report
        if (payrollReportList.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sorry There have been no Payments Yet.");
        }else {
            for(PayrollReportItem payment: payrollReportList){
                try {
                    if ((payment.startOfPayPeriod.after(formatter.parse(txtFirstDate.getText())) || payment.startOfPayPeriod.equals(formatter.parse(txtFirstDate.getText()))) && (payment.startOfPayPeriod.before(formatter.parse(txtSecondDate.getText())) || payment.startOfPayPeriod.equals(formatter.parse(txtSecondDate.getText())))){
                        txtReport.setText(payment.toString()+ "\r\n" + txtReport.getText());
                    }
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Error With The Dates\r\n" + ex);
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnPaymentForPeriodActionPerformed


    
    //event handler for the button that displays 
    //information about all the bonuses assigned to subordinates
    private void btnBonusReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBonusReportActionPerformed
        txtReport.setText("");
        for (Person p: person){
            if (!p.isIsContractor()){
                ISalariedPerson salariedPerson = (ISalariedPerson)p;
                if (salariedPerson.getCurrentBonus() != 0){
                    txtReport.setText(p.getfName() + " " + p.getlName() + " has a bonus of $" + salariedPerson.getCurrentBonus() + "\r\n" + txtReport.getText());
                }  
            }
        }
        if (txtReport.getText().equals("")){
            JOptionPane.showMessageDialog(this, "None of the Subordinates has been given a Bonus");
        }
        
    }//GEN-LAST:event_btnBonusReportActionPerformed

    //event handler for the button that displays all payments for the employee selected in the cboName
    private void btnPaymentHistoryForPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentHistoryForPersonActionPerformed
        txtReport.setText("");
        if (payrollReportList.isEmpty()){
            JOptionPane.showMessageDialog(this, "Theres no record of Payments");
        }else {
            for (PayrollReportItem payment: payrollReportList){

                if (payment.person == cboName.getSelectedItem()){
                    txtReport.setText(payment.toString() + "\r\n" + txtReport.getText());
                }
                
            }
        }
        
    }//GEN-LAST:event_btnPaymentHistoryForPersonActionPerformed

    
    //event handler for the button displaying all fortnightly payments made
    private void btnFortnighlyPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFortnighlyPaymentsActionPerformed
        txtReport.setText("");
        if (payrollReportList.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sorry There have been no Monthly Payments Yet.");
        }else {
            for(PayrollReportItem payment: payrollReportList){
                if (payment.payFreq == TimePeriods.FORTNIGHTLY){

                    txtReport.setText(payment.toString() + "\r\n" + txtReport.getText());
                }
            }
        }
    }//GEN-LAST:event_btnFortnighlyPaymentsActionPerformed

    
    //event handler for the button displaying all monthly payments made
    private void btnMonthlyPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyPaymentsActionPerformed
        txtReport.setText("");
        if (payrollReportList.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sorry There have been no Monthly Payments Yet.");
                
        }else{
            for(PayrollReportItem payment: payrollReportList){
                if (payment.payFreq == TimePeriods.MONTHLY){
                    
                    txtReport.setText(payment.toString() + "\r\n" + txtReport.getText());
                }
            }
        }
    }//GEN-LAST:event_btnMonthlyPaymentsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReportForm().setVisible(true);
//            }
//        });
//    }
    
    //populates cboName with all the perople working in the company

         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBonusReport;
    private javax.swing.JButton btnFortnighlyPayments;
    private javax.swing.JButton btnMonthlyPayments;
    private javax.swing.JButton btnPaymentForPeriod;
    private javax.swing.JButton btnPaymentHistoryForPerson;
    private javax.swing.JComboBox cboName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAssign;
    private javax.swing.JOptionPane msgMessage;
    private javax.swing.JTextField txtFirstDate;
    private javax.swing.JTextArea txtReport;
    private javax.swing.JTextField txtSecondDate;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the person
     */
    public ArrayList<Person> getPerson() {
        return person;
    }

    /**
     * @param person the person to set
     */
    public void setPerson(ArrayList<Person> person) {
        this.person = person;
    }


}
